Fix requiring keyType value. Fix provisor-creator not checking for key validity.

diff --git a/bin/provisor-create b/bin/provisor-create
--- a/bin/provisor-create
+++ b/bin/provisor-create
@@ -10,8 +10,7 @@ trap cleanup EXIT
 # 3. Set users quota
 
 THEUSER=$1
-KEYHEADER=$2
-KEYTEXT=$3
+KEYTEXT=$2
 ERROR=""
 
 TMPKEY=$(/bin/mktemp "/tmp/tmpkey.XXXXXXXX")
@@ -28,10 +27,9 @@ function cleanup
   fi
 }
 
-if [ "$#" -ne 3 ]; then
+if [ "$#" -ne 2 ]; then
   if [ -z "$1" ]; then echo "Error: Missing Username"; fi
-  if [ -z "$2" ]; then echo "Error: Missing Public Key Type"; fi
-  if [ -z "$3" ]; then echo "Error: Missing Public Key"; fi
+  if [ -z "$2" ]; then echo "Error: Missing Public Key"; fi
   exit 1
 fi
 
@@ -41,22 +39,18 @@ if ! [[ ${THEUSER} =~ ^[a-zA-Z0-9_]{4,48}$ ]]; then
   exit 1
 fi
 
-## Validate the given key
-if ! [[ ${KEYHEADER} =~ ^ssh-(rsa|dsa)$ ]]; then 
-  echo "Invalid key" >&2
-  exit 1
-fi
-
-if ! [[ ${KEYTEXT} =~ ^[a-zA-Z0-9+/=]{64,2048}$ ]]; then
-  echo "Invalid key">&2
-  exit 1
-fi
-
 ## Dump the key file somewhere safe
-echo "${KEYHEADER} ${KEYTEXT}" >"${TMPKEY}"
+echo "${KEYTEXT}" >"${TMPKEY}"
+
+ssh-keygen -l -f "${TMKKEY}"
+
+if [ $? -ne 0 ]; then
+	echo "Invalid key!" >&2
+	exit 1
+fi
 
 ## Determine if the user already exists.
-if [ -e "/home/${THEUSER}" ]; then
+if [ -d "/home/${THEUSER}" ]; then
   echo "This user already exists" >&2
   ERROR="no"
   exit 1
